config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html\

  # devise_scope :user do
  #   get '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
  #   post '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
  # end

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'

    end
  end
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
 

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'

  #---- Level 2 ----

  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline]do
  member do
    post '/approve' => "reservations#approve"
    post '/decline' => "reservations#decline"
  end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create] do 
    resources :messages, only: [:index, :create]
  end

  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"


  get '/notification_settings', to: "settings#edit"
  post '/notification_settings', to: "settings#update"

  get '/notifications', to: 'notifications#index'

  mount ActionCable.server => '/cable'

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>

<script type = "text/javascript">

    <% resource.errors.full_messages.each do |value| %>
        toastr.error('<%= value %>')
    <% end %>

</script>

<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
<script type = "text/javascript">
    <% flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
    toastr['<%= type %>']('<%= value %>')
    <% end %>
</script>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "AirMartin", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag search_path, class: "navbar-form navbar-left ",   method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Anywhere", class: "form-control" %>
        </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li >
          <button class="btn btn-form btn-small">
            <%= link_to "Become a host", new_room_path, style: "color: white; text-decoration: none;"%>
          </button>
        </li>
        <% if (!user_signed_in?)%>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li>
            <%= link_to notifications_path do%>
              <i class="fa fa-bell fa-2x icon-babu"></i>
              <span class="badge" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %> &nbsp;
              <%= current_user.fullname%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "Manage Listing", rooms_path %></li>
              <li><%= link_to "List Your Space", new_room_path %></li>
              <li><%= link_to "Your Reservations", your_reservations_path %></li>
              <li><%= link_to "Your Trips", your_trips_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <li role="separator" class="divider"></li>
            </ul>
          </li>
        </ul>
      <% end %>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
<% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/rooms/#{params[:id]}") %>
  <nav class="navbar navbar-default"  style="background-color: #565A5C">
    <div class="container">
      <ul class="nav navbar-nav">
        <li <% if current_page?(dashboard_path) %> class="active"<%end%> ><%= link_to "Dashboard", dashboard_path %></li>
        <li <% if current_page?(rooms_path) %> class="active"<%end%> ><%= link_to "Manage Listings", rooms_path %></li>
        <li <% if current_page?(conversations_path) %> class="active"<%end%> ><%= link_to "Messages", conversations_path %></li>
        <li <% if current_page?(revenues_path) %> class="active"<%end%> ><%= link_to "Manage Your Revenue", revenues_path %></li>
        <li <% if current_page?(host_calendar_path) %> class="active"<%end%> ><%= link_to "Host Calendar", host_calendar_path %></li>
        <li <% if current_page?(payment_method_path) %> class="active"<%end%> ><%= link_to "Account Settings", payment_method_path %></li>
      </ul>
    </div>
  </nav>
<% end %>